const projectsData = [
  {
    id: "01",
    name: "AI Resume & Skill Gap Analyzer",
    cat: "AI",
    badge: "NLP / spaCy",
    desc: "spaCy Named Entity Recognition parsing PDF/DOCX resumes with taxonomy-aligned cosine similarity scoring.",
    web: "https://ai-resume-analyzer-web-nine.vercel.app",
    repo: "https://github.com/tanushkhare/ai-resume-analyzer",
    techStack: ["FastAPI", "spaCy NER", "pdfplumber", "Pydantic v2"],
    endpoints: ["POST /api/v1/resume/analyze", "GET /health"],
    keyFeature: "Eliminates regex counters; categorizes skills across Languages, Frameworks, and Cloud."
  },
  {
    id: "02",
    name: "Autonomous AI Research Assistant",
    cat: "AI",
    badge: "Agentic AI",
    desc: "Agentic research planner decomposing queries into multi-hop literature synthesis with real-time academic validation.",
    web: "https://autonomous-research-assistant-web.vercel.app",
    repo: "https://github.com/tanushkhare/autonomous-research-assistant",
    techStack: ["Python", "FastAPI", "Tavily / ArXiv API", "AsyncIO"],
    endpoints: ["POST /api/v1/research/execute", "GET /api/v1/research/task/{id}"],
    keyFeature: "Replaces hardcoded reference strings with verified DOI/arXiv citation lookups."
  },
  {
    id: "03a",
    name: "Async Real-Time Chatbot",
    cat: "Distributed",
    badge: "WebSockets",
    desc: "Bi-directional WebSocket streaming conversational gateway with session lifecycles and heartbeat monitoring.",
    web: "https://realtime-chatbot-two.vercel.app",
    repo: "https://github.com/tanushkhare/realtime-chatbot",
    techStack: ["WebSockets", "FastAPI", "Redis Cache", "Python AsyncIO"],
    endpoints: ["WS /ws/chat/{session_id}", "GET /health"],
    keyFeature: "Session isolation and memory bounds to prevent event-loop exhaustion."
  },
  {
    id: "03b",
    name: "Vector RAG QA System",
    cat: "AI",
    badge: "Flagship RAG",
    desc: "Dense semantic vector retrieval engine using ChromaDB and all-MiniLM-L6-v2 embeddings with hybrid search.",
    web: "https://vector-rag-qa-system.vercel.app",
    repo: "https://github.com/tanushkhare/vector-rag-qa-system",
    techStack: ["ChromaDB", "Sentence-Transformers", "FastAPI", "PyTest"],
    endpoints: ["POST /api/v1/rag/ingest", "POST /api/v1/rag/query"],
    keyFeature: "Offloaded CPU-bound embeddings using asyncio.to_thread with retrieval latency under 20ms."
  },
  {
    id: "04a",
    name: "AI Meeting Summarizer",
    cat: "AI",
    badge: "Audio / NLP",
    desc: "Whisper-driven speech-to-text pipeline extracting action items, key decisions, and speaker attributions.",
    web: "https://ai-meeting-summarizer-web.vercel.app",
    repo: "https://github.com/tanushkhare/ai-meeting-summarizer",
    techStack: ["OpenAI Whisper", "FastAPI", "Pydantic v2", "Plotly"],
    endpoints: ["POST /api/v1/audio/transcribe", "POST /api/v1/meeting/summarize"],
    keyFeature: "Purged legacy ETL mismatch; replaced with authentic meeting minutes extraction."
  },
  {
    id: "04b",
    name: "Real-Time ETL Dashboard",
    cat: "Distributed",
    badge: "DataOps",
    desc: "Stream data ingestion pipeline tracking real-time throughput metrics, latency bounds, and DLQ quarantined records.",
    web: "https://etl-dashboard-web.vercel.app",
    repo: "https://github.com/tanushkhare/etl-dashboard",
    techStack: ["FastAPI", "AsyncIO", "Docker", "ClickHouse / Postgres"],
    endpoints: ["POST /api/v1/etl/process", "GET /api/v1/etl/telemetry"],
    keyFeature: "Non-blocking event loop execution with strict schema validation."
  },
  {
    id: "05",
    name: "Fake News Classifier",
    cat: "AI",
    badge: "ML Inference",
    desc: "Calibrated neural credibility classifier utilizing DistilBERT transformer models to score misinformative text.",
    web: "https://fake-news-classifier-web.vercel.app",
    repo: "https://github.com/tanushkhare/fake-news-classifier",
    techStack: ["HuggingFace", "DistilBERT", "PyTorch", "FastAPI"],
    endpoints: ["POST /api/v1/classifier/predict", "GET /health"],
    keyFeature: "Replaced mock keyword counters with probabilistic logit classification."
  },
  {
    id: "06",
    name: "Collaborative Real-Time Whiteboard",
    cat: "Distributed",
    badge: "WebSockets",
    desc: "Multi-room collaborative HTML5 canvas engine synchronizing vector strokes with coordinate broadcasting.",
    web: "https://collaborative-realtime-whiteboard.vercel.app",
    repo: "https://github.com/tanushkhare/collaborative-realtime-whiteboard",
    techStack: ["HTML5 Canvas", "FastAPI WebSockets", "Redis pub/sub"],
    endpoints: ["WS /ws/whiteboard/{room_id}", "GET /api/v1/rooms"],
    keyFeature: "Bounded frame buffer preventing memory leaks under high drawing velocity."
  },
  {
    id: "07",
    name: "Placement Management Portal",
    cat: "Distributed",
    badge: "Fullstack",
    desc: "Relational student eligibility screening engine with ACID transactions and SQLAlchemy database lifecycles.",
    web: "https://placement-management-portal-web.vercel.app",
    repo: "https://github.com/tanushkhare/placement-management-portal",
    techStack: ["SQLAlchemy", "SQLite / PostgreSQL", "FastAPI", "Pydantic"],
    endpoints: ["GET /api/v1/students", "POST /api/v1/applications/apply"],
    keyFeature: "Replaced ephemeral dicts with declarative schema dependencies."
  },
  {
    id: "08",
    name: "Voice-to-SQL Query Engine",
    cat: "Distributed",
    badge: "AI Security",
    desc: "AST SQL sandboxing compiler converting natural language to relational queries with AST token protection.",
    web: "https://voice-to-sql-query-engine-web.vercel.app",
    repo: "https://github.com/tanushkhare/voice-to-sql-query-engine",
    techStack: ["sqlglot", "sqlparse", "FastAPI", "SQLite"],
    endpoints: ["POST /api/v1/sql/compile", "POST /api/v1/sql/execute"],
    keyFeature: "Strict table whitelist and AST structural verification blocking SQL injection."
  },
  {
    id: "09",
    name: "E-Commerce Microservices",
    cat: "Distributed",
    badge: "Distributed Systems",
    desc: "High-concurrency checkout and inventory engine protected by per-product asyncio.Lock mutexes.",
    web: "https://ecommerce-microservices-web.vercel.app",
    repo: "https://github.com/tanushkhare/ecommerce-microservices",
    techStack: ["FastAPI", "AsyncIO Mutex", "PostgreSQL", "Pydantic"],
    endpoints: ["GET /api/v1/orders/products", "POST /api/v1/orders/checkout"],
    keyFeature: "Eliminates TOCTOU race conditions under simultaneous order dispatches."
  },
  {
    id: "10",
    name: "Financial Sentiment Streaming",
    cat: "AI",
    badge: "Finance AI",
    desc: "ProsusAI/FinBERT market sentiment classifier streaming polarity impact directly across financial tickers.",
    web: "https://financial-sentiment-streaming-web.vercel.app",
    repo: "https://github.com/tanushkhare/financial-sentiment-streaming",
    techStack: ["FinBERT", "FastAPI SSE", "Transformers", "Plotly"],
    endpoints: ["POST /api/v1/sentiment/score", "GET /api/v1/sentiment/stream"],
    keyFeature: "Domain-specific financial transformer weights replacing generic lexicons."
  },
  {
    id: "11",
    name: "PySpark Distributed Log Analyzer",
    cat: "Distributed",
    badge: "Big Data",
    desc: "Distributed batch processor computing RDD partition metrics, HTTP status distributions, and latency anomalies.",
    web: "https://pyspark-log-analyzer-web.vercel.app",
    repo: "https://github.com/tanushkhare/pyspark-log-analyzer",
    techStack: ["PySpark", "Apache Spark", "FastAPI", "Python"],
    endpoints: ["POST /api/v1/logs/analyze", "GET /health"],
    keyFeature: "Fixed 404 GET/POST mismatches with authentic partitioned RDD evaluation."
  },
  {
    id: "12",
    name: "FinTech Fraud Detection Pipeline",
    cat: "Security",
    badge: "Anomaly Detection",
    desc: "Multivariate IsolationForest scoring transaction outliers across geo-distance deltas and hourly velocity spikes.",
    web: "https://fintech-fraud-detection-web.vercel.app",
    repo: "https://github.com/tanushkhare/fintech-fraud-detection",
    techStack: ["Scikit-Learn", "IsolationForest", "FastAPI", "Pydantic"],
    endpoints: ["POST /api/v1/fraud/evaluate", "GET /health"],
    keyFeature: "Unsupervised anomaly detection identifying zero-day fraud patterns."
  },
  {
    id: "13",
    name: "MLOps Retraining Pipeline",
    cat: "Security",
    badge: "MLOps Flagship",
    desc: "Statistical covariate drift engine tracking Population Stability Index (PSI) and Kolmogorov-Smirnov (KS) tests.",
    web: "https://mlops-retraining-pipeline.vercel.app",
    repo: "https://github.com/tanushkhare/mlops-retraining-pipeline",
    techStack: ["SciPy", "NumPy", "FastAPI", "Streamlit"],
    endpoints: ["POST /api/v1/drift/evaluate", "POST /api/v1/retrain/trigger"],
    keyFeature: "Automated retrain triggers when feature distributions cross PSI thresholds."
  },
  {
    id: "14",
    name: "Packet Sniffer Anomaly Detector",
    cat: "Security",
    badge: "Cybersecurity",
    desc: "Network packet frame parser computing Shannon Entropy to identify encrypted payloads and SYN floods.",
    web: "https://packet-sniffer-anomaly-detector-web.vercel.app",
    repo: "https://github.com/tanushkhare/packet-sniffer-anomaly-detector",
    techStack: ["Scapy", "Python Socket", "FastAPI", "NumPy"],
    endpoints: ["POST /api/v1/network/sniff", "GET /health"],
    keyFeature: "Real frame inspection replacing random number heuristics."
  },
  {
    id: "15",
    name: "Phishing Threat Detector",
    cat: "Security",
    badge: "Security AI",
    desc: "Lexical Shannon entropy scoring, Punycode homograph check, and SSL certificate validity verifier.",
    web: "https://phishing-detector-web.vercel.app",
    repo: "https://github.com/tanushkhare/phishing-detector",
    techStack: ["FastAPI", "tldextract", "Cryptography", "Python"],
    endpoints: ["POST /api/v1/phishing/scan", "GET /health"],
    keyFeature: "Explainable confidence scores breaking down domain signals."
  },
  {
    id: "16",
    name: "DevOps CI/CD Telemetry Dashboard",
    cat: "Security",
    badge: "Zero-Trust",
    desc: "Prometheus cluster metrics harvester paired with server-observed IP origin checks and JWT authentication.",
    web: "https://devops-telemetry-dashboard.vercel.app",
    repo: "https://github.com/tanushkhare/devops-telemetry-dashboard",
    techStack: ["FastAPI", "JWT RBAC", "Prometheus", "Uvicorn"],
    endpoints: ["GET /api/v1/telemetry/metrics", "POST /api/v1/iam/authorize"],
    keyFeature: "True Zero-Trust token authentication replacing client-supplied subnet strings."
  },
  {
    id: "17",
    name: "Serverless File Pipeline",
    cat: "Distributed",
    badge: "Cloud Architecture",
    desc: "Event-driven simulated S3 notification handler with metadata extraction and dead-letter retry queues.",
    web: "https://serverless-file-pipeline.vercel.app",
    repo: "https://github.com/tanushkhare/serverless-file-pipeline",
    techStack: ["FastAPI", "MinIO / S3", "Docker", "AsyncIO"],
    endpoints: ["POST /api/v1/pipeline/process", "GET /api/v1/pipeline/status"],
    keyFeature: "Event-driven asynchronous file routing replacing static Docker stubs."
  },
  {
    id: "18a",
    name: "Smart Face Attendance Biometrics",
    cat: "IoT",
    badge: "Computer Vision",
    desc: "Biometric 128-d face embedding extractor using cosine similarity matching and anti-spoofing verification.",
    web: "https://smart-face-attendance-six.vercel.app",
    repo: "https://github.com/tanushkhare/smart-face-attendance",
    techStack: ["OpenCV", "Dlib / FaceNet", "FastAPI", "SQLite"],
    endpoints: ["POST /api/v1/attendance/verify", "POST /api/v1/attendance/enroll"],
    keyFeature: "Cosine distance matching with persistent attendance logging."
  },
  {
    id: "18b",
    name: "Smart Factory IoT Telemetry",
    cat: "IoT",
    badge: "Predictive Maint.",
    desc: "ISO 10816 vibration analytics engine calculating machine Remaining Useful Life (RUL) degradation curves.",
    web: "https://smart-factory-iot-zeta.vercel.app",
    repo: "https://github.com/tanushkhare/Smart-Factory-IOT",
    techStack: ["NumPy", "SciPy", "FastAPI", "MQTT"],
    endpoints: ["POST /api/v1/factory/telemetry", "GET /api/v1/factory/fleet"],
    keyFeature: "Computes actual RUL curves responsive to sensor vibration amplitudes."
  },
  {
    id: "19",
    name: "Spatial Asset Geofencing",
    cat: "IoT",
    badge: "GIS & Spatial AI",
    desc: "Shapely Point-in-Polygon geometric containment calculator with real-time zone breach tracking.",
    web: "https://spatial-asset-geofencing.vercel.app",
    repo: "https://github.com/tanushkhare/spatial-asset-geofencing",
    techStack: ["Shapely", "GeoJSON", "PyDeck / Mapbox", "FastAPI"],
    endpoints: ["POST /api/v1/spatial/verify", "GET /api/v1/spatial/zones"],
    keyFeature: "Fixed PyDeck polygon accessor bug; real-time perimeter alert processing."
  },
  {
    id: "20",
    name: "IoT Energy & Grid Monitoring",
    cat: "IoT",
    badge: "Smart Grid",
    desc: "MQTT grid telemetry aggregator tracking voltage sag, current harmonic distortion, and cost tariffs.",
    web: "https://iot-energy-monitoring.vercel.app",
    repo: "https://github.com/tanushkhare/iot-energy-monitoring",
    techStack: ["FastAPI", "MQTT Broker", "Pandas", "SQLite"],
    endpoints: ["POST /api/v1/energy/telemetry", "GET /api/v1/energy/alerts"],
    keyFeature: "Purged misplaced GitOps logic; real time-series threshold alerting."
  }
];
